### ISSUE TITLE
Burnout item multiplier doesn't refresh

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#103]
Only got Burnout to about 120% because it didn't transition to second stage. First Freugal fight, all wardens and elite wardens dead. Thrown by Shana like any sane individual would.
[ItemMultiplierBug.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/9634708/ItemMultiplierBug.zip)

**Comment by LordMonoxide** [comment]
I think item magic that requires you to mash isn't working well because it's missing button presses. When I rewrote how input is delivered to the game, I didn't rewrite how the game reads input. It polls the input vars, but a much better way would be to use input events. This will require restructuring parts of various overlays and might be better to do once we're optimized away the memulation.

**Comment by LordMonoxide** [comment]
This seems to be working fine now, closing
