### ISSUE TITLE
Physical ring has no effect

### ISSUE THREAD

**Issue by djcarvey** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#141]
Physical ring states that it increases max HP by 50%. Below is the result of equipping the ring to Rose. Her max HP does not change.
![image](https://user-images.githubusercontent.com/114020799/196003911-d7073ec7-a2d7-491c-9320-08ca4c776caa.png)
![image](https://user-images.githubusercontent.com/114020799/196003921-5bf3afef-6762-4e94-88bc-13c3383f3163.png)

**Comment by djcarvey** [comment]
Extra info from the discord:
https://discord.com/channels/307164262063669248/318595603636551701/1030926880251056239
dragon helm does not work
amulet does work 
magical hat does not work

**Comment by Ink230** [comment]
A)
If HP is set over the max HP limit, the UI and game will update the value correctly. Elsewise the behaviour is still the same where both in menus and in battle the HP values do not get increased. Therefore, the % boosted is being applied, it is just being lost somewhere.

Ex:

Dart has 5000 HP.
Dragon Helm boosts it by 50% to 7500.
Physical Ring boosts it again by 50% to 10000.

Because we've crossed the 9999 max value, the UI and in-game combat values now update to show 9999.

If this does not occur, then no % boost is seen in the UI or in battle.
