### ISSUE TITLE
gpu exception, glError 500

### ISSUE THREAD

**Issue by kwillery** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#260]
Tried on the 221230 build.

CPU: i5-4210
![sc_gpuerror](https://user-images.githubusercontent.com/98255322/220615633-69c1c5ce-7705-4861-bd70-f4a08f6a5fc0.jpg)
(kwazzy on Discord)

**Comment by LordMonoxide** [comment]
This may be due to using GL_RGB_8_8_8_8, though I'm not seeing an extension related to that. I switched to this because it gave the final presentation of the VRAM texture a pretty big performance boost because I didn't have to do as much data conversion on the CPU. If we can find a flag that says whether or not this is supported, we can use that flag to gracefully switch back to the old method

**Comment by dragoonsouls** [comment]
@kwillery have you the graphic card drivers updated?, since i can play this in a laptop that use a very old Intel HD drivers... so maybe something is wrong with them...

**Comment by dragoonsouls** [comment]
I will tell what happened to me recently: randomly SC crashes at start, in my case this happened only in the first seconds of execution and i was messing around with the window, like, rapidly changing the window from the IDE to Discord or from IDE to another thing on windows... maybe lwjgl it's sensible to rapid movements of the context windows the first seconds of execution (this is only a theory)

**Comment by LordMonoxide** [comment]
@dragoonsouls stack trace for the crash you got?

**Comment by LordMonoxide** [comment]
Closing as most of this code has been rewritten
