### ISSUE TITLE
Do power/speed items work?

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#335]

**Comment by Ink230** [comment]
Encounter 457
dart double slash sandworm normal is 682 ✔
dart double slash sandworm powerup is 1023 ✔
dart double slash sandworm powerdown is 341 X

same trend with other additions / party members

• test if powerdown affects dmg of the mob properly
• check again if powerdown lasts forever, more than 3 turns...etc
• check again if powerup last forever, more than 3 turns...etc

**Comment by theflyingzamboni** [comment]
"Power Down lasts forever." Truer words. 😢

**Comment by Ink230** [comment]
## Error Tracing

## Called by script engine
scriptSubFunctions_8004e29c[495] = Bttl_800f::FUN_800f2838;

## Function which is called by the script engine
FUN_800f2838

## Function called by the above
FUN_800f8854

• This checks to see if s2.itemSpecial1_da or s2.itemSpecial2_dc have a value
• If so, applyBuffItem is called for each
• Since items can have ?8 stat changing effects? each time can be called up to 8 times

• This behaviour is seen with the PowerUp and PowerDown items: they are called 4 times each

## Function called by the above
800F92CL
applyBuffItem

• Uses t0 as the attacker and item and a1 as the defender
• a3 is whether the item is a itemSpecial1_da or itemSpecial2_dc, a3_0 is the mem addr for it
• no idea what the turn count is for
• but it uses a3_ as the starting index, and a2 *04L as the offset

• This doesn't seem to be the main cause of the issue

## What we find
Using the above trace, we can get the following info:

**speedup**
• itemSpecial1_da: 0
• itemSpecial2_dc: 32
• itemSpecialAmount_e0: 0
• called once

**speeddown**
• itemSpecial1_da: 0
• itemSpecial2_dc: 16
• itemSpecialAmount_e0: 0
• called once

**powerup**
• itemSpecial1_da: 240
• itemSpecialAmount_e0: 50
• called 4 times

**powerdown**
• itemSpecial1_da: 240
• itemSpecialAmount_e0: -50
• called 4 times


## Summary
• Both Power items are called four times and both Speed items are called once
• This matches their intended stat affected behaviours

• SpeedUp and SpeedDown are missing an itemSpecialAmount_e0 value indicating the Speed items currently do nothing
• PowerDown's itemSpecialAmount is currently -50, which is the opposite sign of PowerUp's value

## Where is the error
**When parsing items from loaded files**
- Signage is not respected
- An offset is getting wild sometime before these items (aka, from bad signage not being respected)
- Inaccurate Ghidra decomp / inaccurate Ghidra decomp translation to Java

Why?
• Other items work as intended (healing, magical attacks, other utility items (?testing needed?)
• The four items are all grouped together: 0xEB, 0xEC, 0xED, 0xEE
• There is a nothing offset right after, which may recover behaviour for the remaining items
• The remaining items do not trigger applyBuffItems / have a separate trace

Where?
• On loading file data
• On assigning file data to memory allocated values
• On reading from memory allocated values
• Script engine error that was "fixed" in a workaround way in retail

Notes
• Notice they use the same ID of 240 for PowerUp and PowerDown yet use a different sign for the value
• Notice in contrast SpeedUp uses ID 32 and SpeedDown uses 16
• Aka, this may have implications inside of the script engine to be aware of, if it is in the script engine
