### ISSUE TITLE
Drake fight causes crash.

### ISSUE THREAD

**Issue by pyrestriker** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#361]
On commit 7372b47, entering the battle with Drake at Shirley's Shrine

![image](https://user-images.githubusercontent.com/3858960/228416759-6eeb5b91-cad3-4710-aec8-00a73226e1ad.png)

**Comment by Ink230** [comment]
• An old unpack of files was letting me get through this cutscene
• On a fresh unpack, I am now getting the error on main

![image](https://user-images.githubusercontent.com/29797557/228419187-d79fccb0-d1d5-4ad0-80e5-7bcf4329e07b.png)

• First loop of the above code iterates to 32 successfully
• Second loop crashes on first index of animIndex = 0

• isMonster is true

---
• This is what it does successfully on the first iteration
![image](https://user-images.githubusercontent.com/29797557/228422419-fc87fbc5-f718-4d3f-8753-8af00bc048b7.png)

vs

• This is what it doesn't do it on the second iteration (notice files is empty)
![image](https://user-images.githubusercontent.com/29797557/228422088-cd800316-6259-4682-bed9-d6a912d121ce.png)

**Comment by dragoonsouls** [comment]
maybe it's saving the space for loading the Bombs animations, since are a different entity in the bosses package... and also in the bosses animation package... for more reference check the TLoD File Mapping (which is available in here: https://docs.google.com/spreadsheets/d/1wso1zNTpeQM2WmxW73-hVLs4bKdGa_6jswWuKdFtavE/edit#gid=1796478097) File 3464, 3920,
