### ISSUE TITLE
Unreversed methods

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#63]
- ~~10b1d8~~
  - ~~during Rose's Death dimension animation, about just after the blood drop~~

**Comment by Zychronix** [comment]
ERROR Gpu Shutting down due to GPU exception:
 java.lang.RuntimeException: java.lang.NoSuchMethodException: legend.game.WMap.FUN_800e7854(legend.game.types.WMapStruct0c_2,legend.game.types.WMapStruct0c_2)
 
 When on the Main Map when pressing the start key the names of towns do not appear. This also affects the Area Map as well.

**Comment by LordMonoxide** [comment]
Fixed world map place name rendering

**Comment by LordMonoxide** [comment]
Changed my mind, I'd rather have separate issues for things that need to be reversed
