### ISSUE TITLE
Started game missing 1hp

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#98]
![image](https://user-images.githubusercontent.com/114179389/191810891-57162e12-f29c-41e6-813b-dcf180be30fe.png)

**Comment by LordMonoxide** [comment]
Can anyone try to reproduce this for me? I think this is the first time we've seen it happen

**Comment by LordMonoxide** [comment]
I just verified this. I started the first fight, got attacked once before I could see my hit points (1 damage), and had 28/30 HP.

**Comment by LordMonoxide** [comment]
This is strange... I just started another new game and I had full HP.

**Comment by dragoonsouls** [comment]
maybe was part of the throwing knife attack, in that moment that attack wasn't visible and sometimes happened to me to be attacked in the first turn in some emulated and hardware runs...

**Comment by Ink230** [comment]
## Main Question
Can anyone still reproduce this? And can they outline the steps of reproducing it?

## Investigation A - setUpNewGameData, Data Tables

Ttle.java sets new game data into the various gameState global variables in setUpNewGameData().

It fetches this information from lookup tables involving starting levels and per character indices of values.

These same tables are used elsewhere throughout the game with no abnormal behaviour detected. Once set, these do not appear to be touched again until the first battle.

A watched variable on charData.hp_08.get() reveals the correct HP values being given every time for all characters.

The rest of the method appears as normal.

When debugging, you can see your live HP from the moment you have control to the first fight either via the main menu or the gameState variable. This always seems to be 30 for Dart.

## Investigation B - Battle Preloading

ActiveStats has simple programming to copy the gameState stat values into the relevant bobj for combat. Even after the assignment, the value still reflects 30 over multiple runs.

## Investigation C - Battle

Obviously, the most likely candidate is the actual event where your HP can change. Was unable to reproduce the bug in any of the following scenarios:

- Dart attacks first
- One soldier attacks with the dart attack first
- Both soldiers attack with the dart attack first
- One soldier melee attacks
- Both soldiers melee attack

I tested each one with 
a) starting a new game from scratch / fresh build to get the right attack pattern
b) saving before the fight and rerolling until the necessary attacks were met 10 times each.

After this, I went to Bttl_800f.java to FUN_800f2500.

I modified this method and all subsequent methods to work in double and fixed any int lossy math operations. At all points in the Java code the double reflected 3.0, 1.0 from the enemies and no "hidden unseen attacks" were caught. When the int cast was required for the script engine, both before and after values of the set and returned script values were 3 or 1. I manually walked through all of this and saw no reason why there could be a rounding or floating precision issue that could sneak an extra damage point in.

## Findings

• I was unable to reproduce the -1 HP bug or notice any errors relating to it while QA'ing
• I do not see anywhere in the sequence where this could occur in the current code base

## If Unreproducible

- The various refactors to the way files are loaded, various script accessor and setter corrections may have corrected this issue
- Particle effects, graphical improvements may have made the dart attack from the soldiers noticeable instead where they may have gone unnoticed very easily, since the issue is -1 HP and their attack does 1 damage
- Other combat related corrections may have inadvertently corrected enemy first attack sequences / scripts that were going unnoticed or unreported (silent fix)

If unreproducible:
- Refers to a much out of date code base
- The issue is stale and should be closed
- Re-open iff it can be reproduced on a confirmed recent build and hopefully with steps to reproduce
